from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('productos/', views.producto_list, name='producto_list'),
    path('productos/create/', views.producto_create, name='producto_create'),
    path('productos/<int:pk>/edit/', views.producto_update, name='producto_update'),
    path('productos/<int:pk>/delete/', views.producto_delete, name='producto_delete'),
    path('productos/exportar/', views.producto_export_csv, name='producto_export_csv'),
    path('categorias/', views.categoria_list, name='categoria_list'),
    path('categorias/create/', views.categoria_create, name='categoria_create'),
    path('categorias/<int:pk>/edit/', views.categoria_update, name='categoria_update'),
    path('categorias/<int:pk>/delete/', views.categoria_delete, name='categoria_delete'),
    path('categorias/exportar/', views.categoria_export_csv, name='categoria_export_csv'),
    path('compras/', views.compra_list, name='compra_list'),
    path('compras/create/', views.compra_create, name='compra_create'),
    path('compras/exportar/', views.compra_export_csv, name='compra_export_csv'),
    path('ventas/', views.venta_list, name='venta_list'),
    path('ventas/create/', views.venta_create, name='venta_create'),
    path('ventas/exportar/', views.venta_export_csv, name='venta_export_csv'),
    path('usuarios/', views.usuario_list, name='usuario_list'),
    path('usuarios/crear/', views.usuario_create_admin, name='usuario_create_admin'),
    path('usuarios/<int:pk>/cambiar-rol/', views.usuario_cambiar_rol, name='usuario_cambiar_rol'),
    path('usuarios/<int:pk>/eliminar/', views.usuario_delete, name='usuario_delete'),
    path('usuarios/<int:pk>/toggle-active/', views.usuario_toggle_active, name='usuario_toggle_active'),
    path('reportes/', views.reporte_view, name='reporte'),
    path('configuracion/', views.configuracion_view, name='configuracion'),
    path('auditoria/', views.auditoria_view, name='auditoria'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
]